baseURL = "https://dr460nf1r3.org/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "congo"
title = "Dragons Lair"
copyright = "Copy, _right?_ :thinking:"
enableEmoji = true
enableRobotsTXT = true
summaryLength = 0

[author]
  name = "Nico Jensch"
  image = "author.png"
  bio = "Just an average Linux / FOSS enthusiast"
  links = [
    { email = "mailto:contact@dr460nf1r3.org" },
    { link = "https://dr460nf1r3.org" },
    { github = "https://github.com/dr460nf1r3" },
    { gitlab = "https://gitlab.com/dr460nf1r3" },
    { telegram = "https://t.me/dr460nf1r3" },
    { twitter = "https://twitter.com/dr460nf1r3" },
  ]
