baseURL = "https://dr460nf1r3.org/"
copyright = ":copyright: 2021 [dr460nf1r3](https://dr460nf1r3.org)"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en"
summaryLength = 50
theme = "congo"
title = "Dragons Lair"

[author]
  bio = "Just an average FOSS enthusiast & distro maintainer"
  image = "author.webp"
  links = [
    { email = "mailto:contact@dr460nf1r3.org" },
    { github = "https://github.com/dr460nf1r3" },
    { gitlab = "https://gitlab.com/dr460nf1r3" },
    { link = "https://dr460nf1r3.org" },
    { telegram = "https://t.me/dr460nf1r3" },
  ]
  name = "Nico Jensch"

[imaging]
disableDate = true
disableLatLong = true
hint = "picture"
