baseURL = "https://dr460nf1r3.org/"
copyright = ":copyright: 2021-2024 [dr460nf1r3](https://dr460nf1r3.org)"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en"
outputs.home = ["HTML", "RSS", "JSON"]
summaryLength = 50
theme = "congo"
title = "Dragons Lair"

[author]
  bio = "Future DevOps engineer & FOSS maintainer"
  headline = "Busy taming dragons.."
  image = "author.webp"
  links = [
    { email = "mailto:contact@dr460nf1r3.org" },
    { github = "https://github.com/dr460nf1r3" },
    { gitlab = "https://gitlab.com/dr460nf1r3" },
    { link = "https://dr460nf1r3.org" },
    { telegram = "https://t.me/dr460nf1r3" },
  ]

[imaging]
  disableDate = true
  disableLatLong = true
  hint = "picture"
  quality = 100
