baseURL = "https://dr460nf1r3.org/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "congo"
title = "Dragons Lair"
copyright = ":copyright: 2021 by [dr460nf1r3](https://dr460nf1r3.org)"
enableEmoji = true
enableRobotsTXT = true
summaryLength = 10

[author]
  name = "Nico Jensch"
  image = "author.png"
  bio = "Just your average FOSS enthusiast & distro maintainer"
  links = [
    { email = "mailto:contact@dr460nf1r3.org" },
    { link = "https://dr460nf1r3.org" },
    { github = "https://github.com/dr460nf1r3" },
    { gitlab = "https://gitlab.com/dr460nf1r3" },
    { telegram = "https://t.me/dr460nf1r3" },
    { twitter = "https://twitter.com/dr460nf1r3" },
  ]
