baseURL = "https://dr460nf1r3.org/"
copyright = ":copyright: 2021-2024 [dr460nf1r3](https://dr460nf1r3.org)"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en"
outputs.home = ["HTML", "RSS", "JSON"]
summaryLength = 50
theme = "congo"
title = "Dragons Lair"

[imaging]
  disableDate = true
  disableLatLong = true
  hint = "picture"
  quality = 100
