[[main]]
  name = "Projects & posts"
  pageRef = "projects"
  weight = 10

[[main]]
  name = "Garuda Linux"
  url = "https://garudalinux.org"
  weight = 20

[[main]]
  name = "Chaotic-AUR"
  url = "https://aur.chaotic.cx"
  weight = 30

[[main]]
  name = "About me"
  pageRef = "posts"
  weight = 40
