[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Garuda Linux"
  url = "https://garudalinux.org"
  weight = 30

[[main]]
  name = "Chaotic-AUR"
  url = "https://aur.chaotic.cx"
  weight = 40
