colorScheme = "congo"
darkMode = "auto"
darkToggle = false
logo = "logo.png"
description = "Linux & tech adventures"
robots = "index, follow"

[homepage]
  layout = "custom"
  showRecent = false

[article]
  showDate = true
  dateFormat = "2.12.2006"
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/dr460nf1r3/website"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showWordCount = false

[list]
  showBreadcrumbs = true
  showSummary = true
  groupByYear = true

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]
