colorScheme = "congo"
darkMode = "true"
darkToggle = false
logo = "logo.png"
description = "Be aware! Linux, tech adventures & dragons inside"
robots = "index, follow"

[homepage]
  layout = "profile"
  showRecent = false

[article]
  showDate = false
  dateFormat = "2.12.2006"
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = true
  editURL = "https://github.com/dr460nf1r3/website/content"
  editAppendPath = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showWordCount = true

[list]
  showBreadcrumbs = false
  showSummary = true
  groupByYear = false

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]
