name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]
    tags:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: pnpm

      - name: Install/Update dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint
